# Generated by Django 4.2.1 on 2023-05-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('capacite', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='salle',
        ),
        migrations.AddField(
            model_name='exam',
            name='salle',
            field=models.ManyToManyField(to='exam_app.salle'),
        ),
    ]
